"""Canonical typed leg contracts for Bongard experiments."""

from .contracts import (
    AffirmativeRelation,
    BOOLEAN_WITNESS,
    FROZEN_VISUAL_SCORE,
    OBJECT,
    PANEL,
    SOFT_SEMANTIC,
    WITNESS,
    ContractViolation,
    InvarianceContract,
    LegContract,
    LegReference,
    LegRegistry,
    LegSemantics,
    Transform,
    TypedValue,
    Unit,
    ValueType,
    implementation_sha256,
)
from .bilateral_symmetry import (
    ALGORITHM_ID as BILATERAL_SYMMETRY_ALGORITHM_ID,
    BILATERAL_SYMMETRY_SCORE,
    BilateralSymmetryInputError,
    BilateralSymmetryObservation,
    bilateral_symmetry_contract,
    bilateral_symmetry_score,
    measure_bilateral_symmetry,
    operation_digest as bilateral_symmetry_operation_digest,
    register_bilateral_symmetry_leg,
)
from .neutral_features import (
    ALGORITHM_ID as NEUTRAL_FEATURE_ALGORITHM_ID,
    EXTRACTOR_VERSION as NEUTRAL_FEATURE_EXTRACTOR_VERSION,
    FEATURE_GROUP_IDS,
    NeutralFeatureExtraction,
    NeutralFeatureGroup,
    NeutralFeatureReceipt,
    NeutralInputIdentity,
    NeutralPacketCommitment,
    extract_neutral_features,
    feature_group_catalog,
    feature_group_catalog_digest,
    feature_space_for_group,
    feature_space_for_groups,
    full_neutral_feature_space,
    project_neutral_feature_extraction,
    verify_neutral_feature_extraction,
)

__all__ = (
    "AffirmativeRelation",
    "BOOLEAN_WITNESS",
    "FROZEN_VISUAL_SCORE",
    "OBJECT",
    "PANEL",
    "SOFT_SEMANTIC",
    "WITNESS",
    "ContractViolation",
    "InvarianceContract",
    "LegContract",
    "LegReference",
    "LegRegistry",
    "LegSemantics",
    "Transform",
    "TypedValue",
    "Unit",
    "ValueType",
    "implementation_sha256",
    "BILATERAL_SYMMETRY_ALGORITHM_ID",
    "BILATERAL_SYMMETRY_SCORE",
    "BilateralSymmetryInputError",
    "BilateralSymmetryObservation",
    "bilateral_symmetry_contract",
    "bilateral_symmetry_operation_digest",
    "bilateral_symmetry_score",
    "measure_bilateral_symmetry",
    "register_bilateral_symmetry_leg",
    "NEUTRAL_FEATURE_ALGORITHM_ID",
    "NEUTRAL_FEATURE_EXTRACTOR_VERSION",
    "FEATURE_GROUP_IDS",
    "NeutralFeatureExtraction",
    "NeutralFeatureGroup",
    "NeutralFeatureReceipt",
    "NeutralInputIdentity",
    "NeutralPacketCommitment",
    "extract_neutral_features",
    "feature_group_catalog",
    "feature_group_catalog_digest",
    "feature_space_for_group",
    "feature_space_for_groups",
    "full_neutral_feature_space",
    "project_neutral_feature_extraction",
    "verify_neutral_feature_extraction",
)
